### ISSUE TITLE
Event page: 2-column text layout

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#107]
We're trying to develop content for the event pages and can't figure out a sensible way to use the existing paragraphs to sensibly layout Programm information ([as seen here](https://codingdavinci.de/events/berlin/#programm)) - it's very structured information that inevitably includes a lot of line-breaks/table rows that we can't put all into one table over multiple columns (the rows won't match up). I don't think there's any way other than some kind of 2-column layout to manage this content. There was a kind of 2-column table layout in the [figma designs](https://www.figma.com/file/W0R4yR7orXG7JhEXlw3Mv6/EventPage-Modules?node-id=0%3A1)... It seems to work almost accidentally ([see here](http://codingdavinci.snater.com/de/events/westfalen-ruhrgebiet-2019))... but if that was intentional then it's not finished. Also I don't think it would work in the way we need if you look at the old website layout... 

Not sure how you would implement this for responsive design... would each column be a separate paragraph? Or would it automatically split one column into 2? I hope there's something in drupal we could use...

**Comment by Snater** [comment]
Hm, I did not interpret the Figma layout as being a layout of two tables next to each other, rather just displaying two variants next to each other because both tables have basically the same content.
I am not sure what to do exactly here.
I could add some right margin to tables, so there would be some space between them, but then tables may never be able to reach across the whole main content container width. In general, having two tables next to each other in one editor element, does not seem the right thing to do as you pointed out.
Tables are, in general, a problematic concept regarding mobiles and editors have to be aware of that.
Anyhow, how about using the "Textblock links/rechts" paragraphs with a text block in the secondary column to have two tables next to each other? Compared to the old site, this seems to be a similar behaviour.

**Comment by lucyWMDE** [comment]
right. the textblock links/rechte Spalte solution gives me 2 text columns (textblock rechts is still broken, not that it's important for this issue). I'll have to play around with it a bit to make sure I can get a layout that looks good, but this issue can be closed for now. thx
