### ISSUE TITLE
Menu: 2nd level navigation

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#113]
I think it's easy for the user to not realise that there's a second level in the navigation. Maybe we need the 2nd level to ausklappen with hover-over or first click... Open to suggestions for the best way to improve this.

**Comment by Snater** [comment]
I am not sure whether that is what this ticket is about, but you can create menu items without them directly linking to pages—I had that as test items in the beginning. So, clicking on a menu item does not necessarily load a new page, but may just unfold the main menu item's sub-menu. In fact, with the current setup, I don't think it makes sense to actually have main menu item's that have sub-menu items, link to pages in general because, as you write, it is not noticeable that there actually is a sub-menu.

**Comment by lucyWMDE** [comment]
I'll test it out as you suggest (make a menu item "Über" with no page, then move the "Was ist Coding da Vinci" page down a level under it) and see what everyone thinks. It seems a bit weird to me though.

**Comment by lucyWMDE** [comment]
uuuh now it's insisting on a link for menu items - can't figure out how to reconfigure it...
![image](https://user-images.githubusercontent.com/42772674/62048213-9d4e0b00-b20c-11e9-9368-0712776b0820.png)

**Comment by Snater** [comment]
I just checked: You just have to enable "Show as expanded (alle Sprachen)" for the menu item to be collapsed and when clicking, the sub-menu items will appear. Practically, it does not really matter what you link that menu item to, because the menu does not work without JavaScript anyway. But I guess it would be most sensible to link it to the first sub-menu item.
