### ISSUE TITLE
Erweiterte Seitenkopf translations

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#117]
For pages that have a bespoke header - I found where translations are made (Struktur/    Blocklayout/Bibliothek benutzerdefinierter Blöcke) and made an English version of the About page...
http://codingdavinci.snater.com/en/block/9/translations
But it doesn't show up on the English version of the page...
http://codingdavinci.snater.com/en/about-coding-da-vinci
Is there something missing somewhere? Or did I overlook some check-box...?

**Comment by Snater** [comment]
Translation block is really a bit of a silly part. It might have been nicer if we could have gone without blocks and use paragraphs for that content as well. Not sure spontaneously, why I did not; Must have been some reason. These header logics are a bit complicated resulting from the design.
Anyway, particular blocks are bound to paths. So, that block was bound to `/was-ist-coding-da-vinci`, but in English, the path is `/about-coding-da-vinci`. So, in the English translation, the block did just not show up. I have added the path to the block config at `/admin/structure/block/manage/extended_header_about`. At the same time, the default page header needs to be hidden on the page, so I also added the path to `/admin/structure/block/manage/relaunch2018_page_title_blank`.

**Comment by lucyWMDE** [comment]
cool.
Yeah - paragraphs might have made the whole thing a lot easier I guess.. The Geschäftstelle is now asking how possible it would be to implement these erweitete seitenköpfe on some other einfache seiten... Ziele, Chancen, Gründer and Dokumentationen. If it's quick and simple pls go ahead with placeholder contents (just reuse the contents from the "Was ist coding da vinci" page) - I assume we can define the contents ourselves in the cms.

**Comment by Snater** [comment]
The problem with these headers are that they are somewhat mixed content with that introduction text that actually is more content than header which is making things complicated. I remember having tried to rip those apart when implementing but combined with the image, everything can only sit properly in one single layout block. So, this implementation is more of a workaround to implement the layout specification. Logically, it would make far more sense to put the introduction text as field into the content type (which would be a simple thing technically), but the problem here is the layout…

I think it might be better if you implement the headers yourself me giving a bit of documentation here:
This is all done in the block layout management that is at _Struktur_ > _Blocklayout_.
1. Add a new _Erweiterter Seitenkopf_ block (tab _Bibliothek benutzerdefinierter Blöcke_ > Button _Benutzerdefinierten Block hinzufügen_ > _Erweiterter Seitenkopf_). You should name the block with something like "Erweiterter Seitenkopf: […]" to ease finding the block when placing it.
2. Add the new block to the _Kopfzeile_ region by going back to the main block layout management page. There, click the button _Block platzieren_ next to _Kofzeile_. A dialogue pops up where you click _Block platzieren_ next to the new block.
3. Hit _Blöcke speichern_ at the bottom of the page.
Now, you just need to configure under what circumstance this block should show up as well as you do not want to show the default header simultaneously:
3.  Next to the new block placed in the _Kopfzeile_ section, click the _Konfigurieren_ button. In the section _Sichtbarkeit_ select the vertical tab _Seiten_ and in the text area enter the path when this block is supposed to show. The easiest thing is to just visit the corresponding page and copy the relevant section from the browser location bar, for the _Ziele_ page it would be `/welche-ziele-verfolgt-coding-da-vinci`. For translated pages, you would need to add the path to the translated page as well in another line in the text area. Be sure _Auf den angegebenen Seiten anzeigen_ below the text area is selected and click _Block speichern_.
4. Click _Konfigurieren_ at the block labeled _Seitentitel (ohne Hintergrund)_ in the _Kopfzeile_ section. Just like in the last step, you add the same path(s) to the text area in the vertical tab _Seiten_. Since _Auf den angegebenen Seiten ausblenden_ is selected there, this default header will not show up on these selected paths anymore.

**Comment by lucyWMDE** [comment]
cool - thanks. We'll give it a try.
