### ISSUE TITLE
option "nicht zutreffend" for source code licences by projects

### ISSUE THREAD

**Issue by ikyriazi** [codingdavinci/relaunch2018#126]
When saving a project with the source code licence option "nicht zutreffend", it seems like the option has not been saved when working later again in"Bearbeitungsmode". Is this deliberate? Wouldn't it be better to be able to see that this option was indeed chosen? (I am talking always about the "Bearbeitungslayer")

**Comment by lucyWMDE** [comment]
@Snater - do you have a good idea for solving this? I assume it's because "nicht zutreffend" isn't a term in the software license taxonomy... is there a way for the form to save the selection of that radio button nonetheless?

**Comment by Snater** [comment]
_nicht zutreffend_ is not a real option in that sense and results from the data model setting: Licence is not a mandatory field (resulting from the intention that project maintainers should not be required to fill all fields at once). And since the field is not mandatory, there needs to be a way to deselect a selected licence. The field consists of radio buttons since a project is allowed have one single licence only.

The field form rendering is as expected according to its configuration. If you want a real _nicht zutreffend_ option, that would need to be added to the taxonomy vocabulary and the field would have to be made mandatory. But I am pretty sure that's nothing that should be done.

**Comment by lucyWMDE** [comment]
Agree. But is there no way to have a default setting of "nicht zutreffend" where no option has been selected?

**Comment by Snater** [comment]
I am not sure I might have a bit of misunderstanding: Do you want _nicht zutreffend_ to be enabled by default, so when no proper option is selected yet or do you want _nicht zutreffend_ to not be listed at all? The second of those alternatives would mean having to make the field mandatory, so the project maintainer has to initially select a licence when creating the project page.

**Comment by lucypatterson** [comment]
Coming back to this... I think it'd be easiest if we remove the "nicht zutreffend" option since it's not a real option. I'd rather make it clearer that adding a source-code license is only necessary where relevant - there can be analogue projects that don't have any software/code component. We can address that by editing the title to "Lizenz des Quelltexts (falls vorhanden)". I'll take care of that - @Snater could you remove the "nicht zutreffend" option? thx

Perhaps more importantly, I think we will have cases where different licenses are used - we have a few cases where there are multiple code-based projects in one CdV project. Would it be easy to switch from radio buttons to checkboxes?

**Comment by Snater** [comment]
There is still misconception about `nicht zutreffend`. However, when switching to checkboxes, which is what I have done now, that option is not required any more / automatically added in compliance with the field settings. So, without additional explanation, it should be fine now. :)
