### ISSUE TITLE
Link to imprint in footer

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#13]
User Storie: As a founder I want to have a link to the Impressum from the landing page/every page so that I comply with DSGVO.

**Comment by Snater** [comment]
https://github.com/codingdavinci/relaunch2018/commit/96168d85c09350d3d6b1d9393e6ead8f5dd00ec3 actually belongs to here. The footer integrates a dedicated menu now (though there is supposed to be just one single item), so linking is done by assigning a page to the footer menu, instead of maintaining a reference to some page manually in the footer.
