### ISSUE TITLE
Projects: field titles should not appear in front-end where field is empty

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#130]
> I noticed that when clicking on "Lizenz der Mediendateien" (in the CMS, just to check what options exist) you get on the front end the heading "Lizenz der Mediendateien" automatically, even if you haven't selected an option. Is there a possibility to get this heading and the respective license, only when an option is actually selected? (e.g. see http://codingdavinci.snater.com/de/projekte/cyberbeetle)

Can we hide the field title "Lizenz der Mediendateien" when no license has been applied? thx

**Comment by Snater** [comment]
The action to remove the media license was hidden. I have fixed that.

I agree it might be nice to have a sanity check for checking whether the licence paragraph is empty, but it's rather complex to check that and, logically, this would also not be the proper approach since, still, kind of empty paragraph references are left in the database. So, the proper way is to simply allow removing the licence paragraph again, which is possible now.

**Comment by lucypatterson** [comment]
we can take care of that in the workflow/freigabe prozess. No problem. 
Thank you!
