### ISSUE TITLE
Datasets import problem?

### ISSUE THREAD

**Issue by lucypatterson** [codingdavinci/relaunch2018#134]
> There might have been a bug while importing datasets from past CdV editions to the new website.
>  
> E.g. the Museum für Kunst und Gewerbe Hamburg has presented three datasets at CdV Nord 2016 (MKG Sammlung Online, Fotografien aus dem Atelier J. Hamann and Japanische Holzschnitte) but only one has been imported.
>  
> Apparently, there’s another problem with the Museum für Naturkunde Berlin. I counted 8 datasets on the new site while the old one lists 13. 

before I go and manually check through all the datasets it'd be great if you could check whether there was a generalised problem with the import... Or share the json file with me so I can try to figure it out for myself. thanks!

**Comment by lucyWMDE** [comment]
dammit wrong account

**Comment by Snater** [comment]
I counted 13 data sets from the Naturkundemuseum Berlin, but the Museum für Kunst und Gewerbe Hamburg has only the Japanische Holzschnitte. This happened due to an inconsistency in the original html file of the old site. Obviously, there was some human error when adding the data sets for that institution in the old site, specifically all the institution's data sets have been wrapped together in a `<div class="data-point">`, which, actually, is supposed to be a wrapper for each individual data set of an institution. The import script is not able to catch such consistency errors in the original file.

**Comment by Snater** [comment]
For completeness, the link to the relevant sections in the source file:
* Naturkundemuseum Berlin, every data set is wrapped in `<div class="data-point">` as expected by the import script: https://github.com/codingdavinci/codingdavinci.de/blob/gh-pages/daten/index.html#L7351
* Museum für Kunst und Gewerbe Hamburg, all data sets are wrapped in `<div class="data-point">`: https://github.com/codingdavinci/codingdavinci.de/blob/gh-pages/daten/index.html#L9509

There is no alternative to checking kind of everything manually. I guess it's hard to even extract the total number of data sets in the old site, because of the html being messy. :-/

**Comment by lucyWMDE** [comment]
ok. thanks for checking on those specific cases... we'll arrange to do a manual check :/

**Comment by lucyWMDE** [comment]
checked through all datasets. Problem solved
