### ISSUE TITLE
Uninstall Update-module?

### ISSUE THREAD

**Issue by mbuechner** [codingdavinci/relaunch2018#135]
Composer is used for updating Drupal. So there's no need for the module Update. Is it possible to uninstall this module?

**Comment by Snater** [comment]
The Update module checks for updates and sends out mails to admins whenever there is some security update. I would not recommend uninstalling it.
https://www.drupal.org/docs/8/core/modules/update/overview

**Comment by mbuechner** [comment]
Drupal admin's shouldn't install any updates. Mails are okay, but any updates via Drupal's backend should be disabled.

**Comment by Snater** [comment]
Related Drupal issues:
https://www.drupal.org/project/drupal/issues/2352637
https://www.drupal.org/project/drupal/issues/2538090

While it would be nice to disable module installations and updates, I don't think it's beneficial to restrict admins in exchange for losing the update notifications. Furthermore, a disabled update module could be re-enabled by an admin at any time and, since it is a Drupal core module, it cannot be uninstalled.

In general, admins should be very aware of what they should do and what not. There are a couple of different user roles that all have limited permissions and the admin role is certainly not recommended for daily use anyhow.

**Comment by mbuechner** [comment]
Ok, That sound acceptable. ;-)
