### ISSUE TITLE
dataset overview sorting/paging problem

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#138]
There seems to be a problem with the dataset overview page, but I'm not exactly sure what it is... here's what I've noticed:
If I filter for "Berlin 2015" i get 3 pages of hits. 
- However, as I click through these pages I see datasets repeated. eg "Manier, Mythos und Moral – Niederländische Druckgrafik um 1600", "Paul Hector Mairs ritterliches Lernbuch", "Mineralogische Sammlungsobjekte", "Die Vogelsammlung des Berliner Museums für Naturkunde", "Notenrollen für selbstspielende Klaviere", "Briefe und Texte aus dem Nachlass von Raoul Hausmann", "Mikroskopische Tausendfüßer-Präparate", "Naturkundliche Zeichnungen von C. G. Ehrenberg" all both come up on page 1 and page 2. "Europeana Collections: 1914 bis 1918" comes up on page 1 and page 3... there may be more repeats.
- Other datasets, at least one, "http://codingdavinci.snater.com/de/daten/ethnologisches-museum-berlin", that should show up for Berlin 2015 don't appear in the list at all.

If I filter for Berlin 2017, Ost 2018, Rhein-Main 2018 I see the same problems.

However, if I filter for Süd 2019 I think I don't see the problem... I think all datasets are presented individually...!

If I filter for "Kunst und Kultur" I see the repetition problem...

**Comment by Snater** [comment]
This is touching some very complex part of the website, as there is some filter customization on top of all these entity references. Basically everything touching data set and project filters are major tasks. There was some problem with removing duplicates while ordering by node creation date. I am not sure, that ordering is actually needed, so I just removed it. If it is needed, I'd need to figure out a more sophisticated solution.

**Comment by lucyWMDE** [comment]
unfortunately the problem is still there. Here's what I see when I filter for Berlin 2015.

-----page1---------------------------------------------------
Bilder von Belegexemplaren aus der Vogelsammlung
Das Datenportal der Deutschen Digitalen Bibliothek
Kriegssammlung der Deutschen Bücherei 1914-1918
Eine sächsische Reise im 18. Jahrhundert
Verknüpfung zur Gemeinsamen Normdatei
Digitalisierte historische Zeitungen
Pflanzenbelege aus dem Botanischen Garten Berlin
Ethnologisches Museum Berlin
Fotografien aus dem Ersten und Zweiten Weltkrieg
Zeugnisse und Geschichten aus Berlin
Portraitindex der UB Leipzig
Titeldaten und Bestandsnachweise der Bibliotheken in Bayern, Berlin und Brandenburg
Mikroskopische Tausendfüßer-Präparate
Briefe und Texte aus dem Nachlass von Raoul Hausmann
Die Schulbücher des Georg-Eckert-Instituts
Spielen im 20. Jahrhundert: Konsolen und Computer
Holocaust­ und Lagerliteratur (1933­ - 1949) ­
Europeana Collections: 1914 bis 1918
Handschriften aus Charlottenburg
Paul Hector Mairs ritterliches Lernbuch
Stoffmusterbücher aus dem Historischen Archiv der HTW
Druckgrafische Arbeiten von Hermann Struck (1876-1944)
Raubfliegen (Asilidae) im Bild
Buch-Netzwerk in Leipzig 1913

-----page2---------------------------------------------------
NS-Zwangsarbeiterlager in Berlin
*Europeana Collections: 1914 bis 1918
*Ethnologisches Museum Berlin
*Stoffmusterbücher aus dem Historischen Archiv der HTW
*Druckgrafische Arbeiten von Hermann Struck (1876-1944)
Tanz und Theater: Mediathek des Mime Centrums
Patente und ­Zeichnungen aus den Jahren 1840­-1877
*Handschriften aus Charlottenburg
Paul Hector Mairs ritterliches Lernbuch
Reisefotografie - Oswald Lübeck & Franz Grasser
Blumenmoden, Zeitgeschmack und Weltbezug von 1700 bis 1900
*Raubfliegen (Asilidae) im Bild
Bibliotheca Gastronomica
Fotos von Schwalbenschwänzen und Weißlingen
Die Dresdner Bilderhandschrift des Sachsenspiegels
Fotografien aus dem Ersten und Zweiten Weltkrieg
Maya-Handschrift aus dem 13. Jahrhundert
Politische Karikatur für Kinder
Regesten von Urkunden der Kaiser, Könige und einiger Päpste des Mittelalters (800 bis 1500)
Siegelmarken zwischen 1850­-1945
Zoosphere: Hochauflösende sphärische Bildsequenzen
Naturkundliche Zeichnungen von C. G. Ehrenberg
Historische Hamburg- und Elb-Karten 1588 – 1939
Mineralogische Sammlungsobjekte

------page3--------------------------------------------------
*Raubfliegen (Asilidae) im Bild
*Titeldaten und Bestandsnachweise der Bibliotheken in Bayern, Berlin und Brandenburg
**Siegelmarken zwischen 1850­-1945

* - duplicate from page 1
** - duplicate from page 2.

This is a problem we need to fix. It doesn't matter what order the datasets appear in - I think we originally talked about creation date to have a pseudo-random order, avoiding alphabetical sorting... But duplication within filter constraints is not ok. Fixing this is the first priority. I'll take whatever sort order we can get.

**Comment by Snater** [comment]
No time to panic just yet. :D

Spent a while with that now. This is one of the weirdest issues I every experienced—not kidding. How could I miss out on something that still is that obviously broken? First off, I missed out on testing the fix online, just because I did not see any reason why this should work differently on the server. I checked those three pages over and over, as far as I can tell _it is working correctly locally_. I figured out the ordering in the sub-query (not the one in the outer query that has already been removed) is still causing trouble. (Actually, ordering by creation date as planned should still have been fine so far.) I tried multiple combinations/alternatives of defining the creation date order, but all failed. So, eventually, ordering is removed completely now and it should work in terms of not displaying duplicates as to what I can see when clicking through those three pages of the Berlin 2015 filter online.

I suppose the error is caused by mismatching databases. The server runs MySQL 5.6.44, while my local XAMPP is running MariaDB 10.1.32. I am really sceptical on that aspect being the issue, but it seems to me…
This might be a bug in MySQL, or a specification gap. The queries for each page are issued with LIMIT and OFFSET. I have the suspicion that in the different databases, the offset is evaluated at different stages when compiling the query result—before or after running DISTINCT. Or DISTINCT is just working differently.

So, for now, this should work, but without sorting by creation date of the data set node. I could look more into finding a work-around making things more complex, but, alternatively, we might just be able to run MariaDB instead of MySQL on the server the site should be migrated to. Then, hopefully, re-enabling ordering should just work out fine. I could also have a look whether some more recent MySQL version (5.6 is from 2013—but MariaDB 10.1 is also just 2014) does similar processing.

Sorry for that hassle.
