### ISSUE TITLE
Dataset: unpublishable dataset

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#140]
We have a mysterious problem 
http://codingdavinci.snater.com/de/daten/geschichtliches-ortsverzeichnis-gov
This dataset was previously online. We had to edit the license but now we seem to be unable to publish it - the only option we have is "unveröffentlicht". 

I'm wondering if it's a rights issue - that the institution that submitted the data should approve the edits. If that's what it's about then we haven't quite got it right yet...it should be possible to offer the institution a draft version for approval, but not necessary. We have to allow admin, Geschäftstelle and regional organiser accounts to make those kind of edits without the institutions approval if necessary. The same will be true for projects, if it's not already set up that way. Could you reconfigure it?

**Comment by Snater** [comment]
Yes, sure, my bad. Was stuck on unpublished, because there was no content moderation flow to republish. This is not directly related to the approval workflow. This is not affected.

But just for the un-publishing, this was supposed to only be available for admins/Geschäftsstelle users, so I made republishing also available only to those users.
