### ISSUE TITLE
General: 2 Sprachigkeit 

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#16]
User Storie: 
2-SPRACHIGKEIT: 
As a international hackathon participant I want generic information about CdV in English so that I can quickly understand if I’d like to participate.

As a international GLAM decision maker I want generic information about CdV in English so that I can understand the concept and get in touch.

Dev Comment:
We need the option of producing multiple language versions of content, but not universally - will mainly be used on some static pages (about us, FAQ…)

**Comment by lucyWMDE** [comment]
Design (& dev) comment:
Relatively few pages will have alt-language content. So - better to show an indication at page level where an alt-language version is available, rather than give the impression you can switch the whole site to the alt-language.

**Comment by Snater** [comment]
Just noting this issue depends on all content types being implemented, as every (input) field that shall be translatable needs to be tagged.

**Comment by Snater** [comment]
The language switcher is implemented. I extracted colours from the screen designs, but the states "disabled" (no translation available) and "inactive" (translation available, may switch to language) look rather similar at the moment.

**Comment by lohengruen** [comment]
When no translation is available, we could use a transparency of about 25% for the disabled state.
When a translation is available, the active language should be white* with a 100% opacity and the inactive one should have a opacity of around 50%.

*: For most headers and key visuals, a white font with a slight shadow works best. However, since the key visuals are probably changing, the color of the language switcher might also need to change...

**Comment by Snater** [comment]
This should generally be done. I enabled translation on every field where it makes sense. That setup might need some tweaking, but than can be done anytime.
