### ISSUE TITLE
Landing Page/News overview: teasers

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#165]
- [ ] Date and author are in light grey in figma - pls adjust. Author link should follow new link style (same colour as text would otherwise be, medium)
- [ ] Spacing above and below header is, I think, more than in Figma.
- [ ] Teaser body text should be grey (4F4F4F) rather than green.
- [ ] Seems to be an issue with thumbnail image-stretching for teaser “Halbzeit!” - can we fix that?

Tags

- [ ] No tags in the teasers on landing page - this was intentional - we think they don't add any information there pls remove.
- [ ] tags in news overview page should be 22px high, not 24px.

**Comment by Snater** [comment]
Should be done except for the tag style (created #194) and the author link which I don't know what that is referring to. News article authors are not linked so far. If they should, please create a new feature ticket.

**Comment by Snater** [comment]
No, I am wrong. Authors are actually linked. I was just not in my mind, because I was not aware of the links actually making sense at the moment. They lead to the user page, but we do not have a concept for user pages. Alternatively, it should be possible to use the author link as a filter on articles, but would that really be a useful feature? So, the concept of the author link might be a bit underspecified. :)

**Comment by lucyWMDE** [comment]
ha. I think I'd never actually clicked on an author to see what it links to. I don't remember asking for it so I wouldn't have specified anything. I think a filter by author would be the only useful thing to link to, but I'm not sure it's really that useful. Happy to just remove the link.
