### ISSUE TITLE
Einfache Seite: link styles

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#169]
- Basic links should have same colour as text would have by default… therefore, body text links should be black. Currently this is mostly true. However, 
    - body text links within Abschnitt "Text" lists, 
    - Bildunterschriften/Quellen, 
    - News article date/author info 

    ... are all still green - [eg see here](http://codingdavinci.snater.com/de/einfache-seite-titel) - please change to black for consistency. Font weight should be medium (500? - it’s implemented as 600)
- It’s not exactly clear from Figma, but I think text of special link styles (“link mit Pfeil”, “verlinkte email address”) should be green to match the arrow/mail icons. Not sure here whether font weight should be medium (500?) or regular (400?) as on this page.

Stephanie - please confirm.

**Comment by stffb** [comment]
— Links with the arrow will always be green and not underlined as hover state. Only change into dark green!

**Comment by Snater** [comment]
I am sure this is not completely resolved, but closing for now. There might be some regression and link styles that are still not as expected. Just reopen or create a new issue. The link styles are a just bit confusing to me, which is why I had not put too much focus on it so far. I don't think it's optimal to have the link styled in the same colour as the default text colour without underlining.

**Comment by lucyWMDE** [comment]
reopening and assigning to me to check implementation.
