### ISSUE TITLE
General:  Menu

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#18]
As a founder I want a good solution for the 2nd level navigation so that multiple events can be listed and easy to find (at least the upcoming ones).

As a founder I want to be able to add/edit top-level pages so that we can adapt if the coding da vinci project changes over time.

Designer: Q: should we list events in 2nd level navigation?

Developer: 2nd level nav (used for Events and About us) will likely have 2-4 menu items.

**Comment by samu-wmde** [comment]
@lucypatterson  GDPR problems

**Comment by lohengruen** [comment]
here's a quick demo I made of the overlay menu. It doesn't have a second level yet and the motion is different from what I'd like, but its a basic version.
@Snater , do you think we can work with this kind of code? Or does Drupal do things differently?

https://codepen.io/anon/pen/KxRBNQ

**Comment by Snater** [comment]
@lohengruen: How shall the mobile main menu's second level look like?

**Comment by lohengruen** [comment]
Hey Henning, I just checked out the preview, it looks great so far! I really like how the menu behaves, especially the icon transition.

About the mobile version: It probably makes sense to adjust the font size according to the screen size, for example 
`font-size:8vh `
will make sure that the menu is always visible on every screen. If we want to be fancy about it, we could even have something like
`font-size: calc(12px + .5vw);`
This sets the minimum font size at 12px and amplifies it by .5vw depending on the viewport width.
The same would work for line-height.

The second level of navigation should extend to the right, as you already implemented on the preview. On mobile it should behave the same way - if we can make it work with a smaller font size. It shouldn't look too crammed of course. It looks fine with menu items that have a normal length (max. ~10 characters, like "Rhein-Main") but with longer names it quickly becomes very narrow (eg. "Untermenupunkt 1.2").
Alternatively, we could of course use a simple accordion effect, so that the second level is displayed under the clicked first level menu item. (which would probably create the need to have the menu scroll vertically on small screens)

Also, some minor design changes to the menu:
Can we make the fonts a little bit thinner? Using Medium (font-weight:500) for level 1 and Light for Level 2 (font-weight:300) makes it less crowded when we compress the menu.

And the X in the menu item should be replaced by a geometric X. I've included a svg. in the Figma file, but if it's easier to use for you, we could also include the symbol in our icon font.

I've updated the menu designs in this file:
https://www.figma.com/file/JkjRyPRQpgIodPhxYPb8JB/LandingPage-Design-B-Typographic?node-id=0%3A1

**Comment by Snater** [comment]
I think we need a more robust concept for the menu. Using vh may lead to unexpected results as we cannot always be sure on the viewport format.

**Comment by Snater** [comment]
I think we can close that for now. I checked the menu again and applied some overflow rules. Technically, the menu is working as far as I am aware, even in IE to an, I'd say, acceptable extend. If we are going to revisit the menu at some point, let's start a new issue then.
