### ISSUE TITLE
Dataset overview page card design issues

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#203]
dataset overview page...
![image](https://user-images.githubusercontent.com/42772674/87569217-13ba7600-c6c7-11ea-8b86-46733952c264.png)

Check how it's done on the Projects overview page - spacing between title <> description as well as description <> tags and between the tags themselves looks balanced there.
![image](https://user-images.githubusercontent.com/42772674/87569393-57ad7b00-c6c7-11ea-8331-b2220b539a66.png)

- TAGS: dateityp tags are fine, but there's too much horizontal spacing between event tags - should only be 8px.... You particularly notice it when a dataset has been submitted to multiple cdv events - see DDB API dataset card in the screenshot at the top.
- TYPOGRAPHY: spacing between dataset title and institution is too large (suggest remove 16px bottom margin?), spacing between institution and first row of tags is too small (suggest add 16px bottom margin?).

**Comment by Snater** [comment]
Let's try this. I am not sure I get that with the spacing between title and institution. The institution name is just aligned to the bottom of the header block as the short description on the project page in the Figma design. Yet I adjust the overall padding a bit because it was obviously a bit wrong missing out on considering the navbar height. Just reopen if the institution name should be placed differently.

**Comment by lucyWMDE** [comment]
hmm.. this issue was about the cards on the dataset overview page, not the single dataset page (so it wouldn't have anything to do with the header block). Still the single dataset page looks good so thx! I'll add some more detail to the original issue description...

**Comment by Snater** [comment]
Data set teaser on the view page looks proper now, I think. Hopefully also no regression on some other page.
