### ISSUE TITLE
Single dataset page

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#205]
Event tags at top of page should all be in one line with no linebreaks. 
eg here http://codingdavinci.snater.com/de/daten/das-datenportal-der-deutschen-digitalen-bibliothek

**Comment by Snater** [comment]
The object type tags were also not inlined properly. But they are not.

Yet making the event tags and the object type tags display in one line is not trivial. It will take some effort because the rendered data structures are very different and it will probably require a few additional individual templates just for this effect. I left this untouched for now, if I should take the effort, reopen.

**Comment by lucyWMDE** [comment]
> making the event tags and the object type tags display in one line is not trivial. It will take some effort because the rendered data structures are very different and it will probably require a few additional individual templates just for this effect. I left this untouched for now, if I should take the effort, reopen.

Looks like it's already done... eg
- http://codingdavinci.snater.com/de/daten/heinrich-zille-als-fotograf
- http://codingdavinci.snater.com/de/daten/ethnologisches-museum-berlin

Confused, but thanks!
