### ISSUE TITLE
Event team can't access own event after end date

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#222]
Currently, event team user only has access to the event to which they are assigned from creation until the end date of the event. Event team user needs to be able to access, edit, save draft, and publish their event even after it is over.

**Comment by Snater** [comment]
This must be something different. There is no date check on the access.

I noticed that some events were saved by the admin user who has permission to use the restricted HTML text format which, so far, the event team was not allowed to use. What I did now is to allow the even team to also use the restricted HTML text format. I am not sure that is what is supposed to be, but I could imagine that is the actual issue here.

If text format assignment should be different, just create a new issue.
