### ISSUE TITLE
language switching on project and dataset overview pages

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#230]
For some weird reason, switching languages on the project and dataset overview pages using the controls at the top right of the screen causes filters to be applied:
- for the projects it's the "VR/AR" Projekttyp filter. 
- For the dataset overview page, it's a selection of 3 Thema filters (Geschichte und Geografie, Medizin und Gesundheit, Politik und Militär)
This should not be happening. 

Secondly, I'm having trouble pinning it down, but the language controls style for "language selected" (i.e. the chose language is shown black with a white background) isn't applied consistently. Sometimes I can toggle between languages and the style is correctly applied, sometimes (perhaps when after I clear the weird filters) it doesn't appear - it looks as though no language is selected.

Lastly, I would expect to see the translated texts on the project/dataset cards, where available, when I switch language. E.g. there are french translations for all the Saar-Lor-Lux 2020 datasets... so the dataset titles should show here in French: http://codingdavinci.snater.com/fr/daten?search=&institution=&event%5B0%5D=1770

**Comment by Snater** [comment]
1. Cannot reproduce, might also due to some strange caching. Never experienced similar behaviour. But if it is still there, please create a new issue. This issue should have been three.
2. Also never experienced that. The hover style was not nice with the text getting black on that dark background. I fixed that. This could also be related to caching. In theory, content can be created without any language assigned which would then the language switcher to not have any language selected. I need some steps to reproduce this.
3. That should hopefully work now with the interface language being used when rendering the relevant views.
