### ISSUE TITLE
Migration to DNB servers

### ISSUE THREAD

**Issue by mbuechner** [codingdavinci/relaunch2018#244]
For the data migration to the servers of DNB we need...

- database dump
- all static files (usually in folder `\sites\default\files\`)

Which database do we need? Is MariaDB 10.5.4 okay?

Contact: https://pro.deutsche-digitale-bibliothek.de/user/37 :smile:

**Comment by mbuechner** [comment]
I got everything from @Snater and I've done my part. Could you please check if everything works as aspected, @lucyWMDE and @Snater ?

https://test.codingdavinci.de/

**Comment by mbuechner** [comment]
To access what, @Snater?

**Comment by lucyWMDE** [comment]
Hi @mbuechner, I assume it's this (I realised you don't see the login details when you use chrome - I emailed him with them this week)... but his commits also need to be pulled... and in a timely manner so that we can test and give feedback if needed. Is there a way that he can have access to do that? If not you two will need to figure out an efficient way to do that between you.

**Comment by mbuechner** [comment]
It's not allowed to deploy any software from outside the DNB. Sorry!

But, simply create a new [release](https://github.com/codingdavinci/relaunch2018/releases), like L already did, and write a short email to @ikyriazi or me to ask if we could deploy ' v1.0-beta?' for you. That'll be done within minutes!
