### ISSUE TITLE
Implement screen designs

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#27]
- [x] basic drupal install, staging area, composer & github, bootstrap framework
- [ ] set up content types
- [ ] set up user-management
- [ ] implement basic background design & templates
- [ ] implement key visuals

**Comment by Snater** [comment]
I created #28 regarding content moderation which is somehow connected to user management. Ideally, instead of a checklist, all items would be individual issues, so commits may reference specific issues. (When committing to the repository, the issue number can be specified automatically leaving a reference in the issue ticket.) Github does not support parent issues, so I guess an issue like that should probably be a milestone.

**Comment by Snater** [comment]
@lohengruen @lucyWMDE 
I have not implemented any page header properly yet. "Impressum", login page, news pages, "Presse" and FAQ page are basically just missing the header styles. Are those pages' headers final as to the screen designs or do they need approval / do they depend on the key visuals?

@lohengruen Is there anything left to do on the final icon font -- when will it be available?

**Comment by lohengruen** [comment]
The content of the headers may change, with which I mean the dimensions and the background image. However, the headline and sublime of the header and additional content (e.g. tags in News) will most likely stay the same.

There's a new version of the icon font here (added new X for menu, thicker curly brackets, RSS icon and some misc. stuff):
https://www.dropbox.com/sh/x9364kp7uvf8yhe/AADlBtlxGh1SPnwjtOPUHJtaa?dl=0

**Comment by lohengruen** [comment]
just a minor detail, but you can get the new favicon / app icon here:
https://www.dropbox.com/sh/g3nwhxt6sq7g4kb/AABvKRVc9pAAOBr1S9aDpAXya?dl=0

**Comment by Snater** [comment]
The scope of this ticket is too broad. I will add more specific tickets on upcoming issues.
