### ISSUE TITLE
update info for Chronoscope Hamburg

### ISSUE THREAD

**Issue by mprove** [codingdavinci/relaunch2018#291]
Chronoscope Hamburg https://codingdavinci.de/de/projekte/chronoscope-hamburg

Benutzte Datensets
- Mit Niederländischer Druckgraphik hat das Chronoscope nichts zu tun; statt dessen…
- a) https://codingdavinci.de/daten/historische-hamburg-und-elb-karten-1588-1939
- b) https://codingdavinci.de/daten/historische-kartensammlung
- c) https://codingdavinci.de/daten/preussische-landesaufnahme-chronologen
- d) https://codingdavinci.de/daten/druckmaschinensounds
- e) https://codingdavinci.de/daten/hamburger-architekturfotos-der-1920er-jahre

**Comment by mprove** [comment]
fixed; new URL https://codingdavinci.de/projekte/chronoscope-hamburg-chronoscope-world

**Comment by ikyriazi** [comment]
Dear @mprove,
I removed the "Pläne und Fotos Kraftwerk Hirschfelde"-dataset from the list, because there should be no dataset-related projects on our website **before** the Kick-Off (taking place on March 19/20th). You are very welcome to add your project after the event! Thank you and all the best.

**Comment by mprove** [comment]
ok, though I’ve added this to reach out to future teams. 
/cf. https://twitter.com/hashtag/kraftwerkhirschfelde?f=live

**Comment by ikyriazi** [comment]
I re-linked the "Pläne und Fotos Kraftwerk Hirschfelde"-dataset.
