### ISSUE TITLE
Creating a single Event Page 

### ISSUE THREAD

**Issue by samu-wmde** [codingdavinci/relaunch2018#3]
Presentation of Coding da Vinci events. Each made up of multiple parts over several months: onboarding events > kick-off weekend > sprint phase > Award ceremony. 1 scrolling page is enough (no sub-pages needed). 

As a regional organiser I want to easily create and update content on my event page so that I can develop rich content quickly and easily.

As a founder I want creation of “Event X” to be tied to the creation of a new category “Event X” applied throughout the website (dataset & project archives, news) so that all event content is linked.

**Comment by samu-wmde** [comment]
@lucypatterson Cleaning this task up

**Comment by lohengruen** [comment]
Wireframe
https://www.figma.com/file/tdfEKrzA5eBrRv0d1zGMu4/EventPage-Wireframe?node-id=1%3A2

**Comment by Snater** [comment]
A few questions on the screen design to make things clearer for me:
- Will there always be exactly 4 tilted squares ("Infotour 2018", "Kick-Off", …) in those colours? I am not sure how to prevent editors from not entering text that is too long or contains long words that do not wrap (word-break is rather unelegant).
- Where do the challenges come from (meaning at what stage is that content supposed to be created)? Are these per event or globally embedded in every event's page?
- Just to be sure: "Veranstalter" != institutions providing data sets for the event?

**Comment by lohengruen** [comment]
• I can see the problem. If it were a normal square, the css could easily contain the text (with something like overflow:hidden), but since it's tilted this becomes tricky. I will do some research on this. The only idea I have at the moment is to contain the text inside a invisible circle that is inside the square. (A bit clumsy, I know ;)

• The challenges are just a placeholder for any kind of box with image and text inside. At the moment we only need them for some of the event pages (if the creators have one content that fits), but I can image them being useful somewhere else on the page (e.g., the dataset thumbnails on the Daten page are very similar:
https://www.figma.com/file/dnh4F4VAXHUwLCW7dH29gUdM/Data-Wireframe
With the challenge boxes as well as with the tilted squares the idea is to give the event organisers a building block system that they can use to create an event page that fits their information and is also distinctive to the other event pages. We will probably create more building blocks in this style.
 
• I agree, Veranstalter is not a really fitting name for this, but I can't think of a better alternative

**Comment by Snater** [comment]
- OK, I was thinking about rotating the square containing the text by 45° and the text alone -45°, but I am not sure that would work out, text rotation is not very well supported by now. But my concern was more about the available space for the text in general for the moment.
- OK, I get the idea.
- I didn't think about the name (wording is not my business anyway ;) ), it's about the content. Whether Veranstalter logos shall be added manually to the event in contrast to automatically pulling those from the institutions, which have their own content or user type. Does the set of Veranstalter match the set of institutions providing data sets for that event? Or does that not matter, because logos shall be added to the event anyway?

**Comment by lohengruen** [comment]
• thats a good idea with the rotation. We could test it for the moment, and if it's not working properly, we could think about doing a different design. I'm not too fixated on this design and can try out different stuff. But all ideas will probably have in common that we either need to limit the number of characters in the element or need to set the font size to scale automatically
• 👍
• As far as I know, at the moment the event organisers collect all the logos and upload them. Which I'd prefer, because I'd like to tint all the logos in one particular color. This could either be done manually in Photoshop or other software, but it would also be possible using SVG filters right in the backend. I'll try to make a CodePen demonstrating the color-effect.

**Comment by lucyWMDE** [comment]
to the "Veranstalter" issue, they are the institutions/organisations that make up the regional event team. i.e. Veranstalter != data-contributing institutions. They won't exist or be used in the system elsewhere, so it's probably enough to just upload them manually.

**Comment by lucyWMDE** [comment]
We actually have a whole system for the different logos that should be on this page:
- Veranstalter = logos of regional organising team
- Partner = funding / in-kind contribution, highest level
- Förderer = funding / in-kind contribution, medium level
- Unterstützer = funding / in-kind contribution, lowest level
Officially there aren't supposed to be any "Sponsoren" due to constraints of at least one founder... however, some regional teams ended up using this phrasing... Would be best if we can keep it flexible. None of these logos would appear elsewhere on the site, so could be uploaded directly here.

@lohengruen so far we don't have the logos of the data-contributing cultural institutions on the events page. So far they are only listed on the [Dokumentation](https://codingdavinci.de/dokumentation/) page. The idea was to shift the content from the Dokumentation page to the archive event pages so that we no longer need the Dokumentation page. However, we'll probably need a different kind of layout so that we don't just fill up the whole page with logos... Let's talk again about the content of the event page and finalise before we go further with implementation of this screen design.

**Comment by lucyWMDE** [comment]
@lohengruen here you can find the contents (mainly just headings) of the single event page: https://docs.google.com/document/d/12TjhDurZiWg08Bnz_SMzl4bXo5m5eBxAafN1AyNV_FA/edit#heading=h.bx7f036gu1sf - some of it is new (the post-event documentation parts) so please think about an appropriate layout... ideas on the old CdV Nord event page.

**Comment by lohengruen** [comment]
About the rotated squares: The only viable solution I see would be to use images for the squares (instead of divs with real text). But I agree with Henning, we might spend too much time for such a minor detail and it might cause some weird problems, so I think its best to come up with a different design. I will include something in the new event page screen design, along with the new content. I'll have it finished  tomorrow.

**Comment by Snater** [comment]
@lohengruen Module "Image Left & Right": What is meant by "… or centered without text" in the explanation? I suppose there will always be some text for images (at least the attribution). More importantly regarding the layout, I don't think it will work out properly to center the image on one column and put the text next to it. If we want to center an image, the text should probably also be below the image. Then again, how do we determine the maximum image height (or width) when an image shall be centered? I don't think we can assume proper exact size of the original image uploaded. Is the different image caption colour on the two examples intentional?

(I don't think it's relevant, but I am going to combine "Text Block Left & Right" and "Image Left & Right" by implementing a text block left and a text block right paragraph type, both with an optional image, so we have only 2 instead of 4 paragraph types in that purpose.)

**Comment by Snater** [comment]
@lohengruen Module "Tables": How flexible is the table style/layout meant to be / will there only be that particular use-case for tables? For example, will the style of each column always be like that or is the content editor supposed to assign styles per column (cells)?
Technically, instead of implementing a dedicated table paragraph, it is a lot easier to have a full-width rich text paragraph that allows placing a table. We can assign a table style to switch the table colour scheme and we could of course apply column styles by that "global" table style as well--if column styles are supposed to be fixed. Then again, if styles are fixed, how would a fourth column look like? Or is the use-case limited to three columns?
Detail: The green background is not part of the colour palette, contrast of that green to white is quite low (https://contrastchecker.com/?c=FFFFFF&b=D0E8E2).

**Comment by Snater** [comment]
@lohengruen @lucyWMDE Module "Button": Will there be only those two buttons ("Newsletter abonnieren", "Jetzt registrieren!") or should that be somewhat flexible?
If there should only be those two buttons, I would probably implement a paragraph for each button, as that is less prone to errors from a content editor perspective.
If it should be flexible (there may be more buttons with other icons now or in the future etc.), I would implement styles that could be applied to links in a rich text field. (As noted above, there will be a full-width rich text paragraph anyway, so buttons may be centered across the viewport width.)

**Comment by Snater** [comment]
As for the screen design, I will implement all modules as paragraphs, so they can be added optionally to an event page. I would just make two exceptions to that:
- The text intro, because, I assume, there should always be just one text intro block, which would be on top of the page. (If the intro block is left blank, it would just not show up on the page.)
- The block with the winners. This is structurally important, because the winner info will be gathered when displaying projects in the project archive, so we need a definitive structure where this information is defined. We could have that as one of the individually added paragraphs as well, but that would not be a solid solution and would make things technically complex.
A little downside of that would be that, in the layout, that block cannot just be placed anywhere between all the other paragraphs added to the paragraph section. But if it's fine if the block with the winners (as soon as it's filled with information) would always show up either right below the intro text or at the bottom of the page, we are good to go. Alternatively, there could be two paragraph sections, one above and one below the winners block.

**Comment by lucyWMDE** [comment]
Cool.

- fixed (optional) intro text makes sense
- Happy for this block to have a fixed position. Top of the page under intro text would be better than bottom. All I can think is that some teams might have a film about the event they'd rather run at the top of the page.. but we can live with prizewinners fixed at the top.
- please hold back on implementing the timeline paragraph - we haven't yet made a decision about which version we prefer.

**Comment by lucyWMDE** [comment]
Further general paragraph styles are in the [Design system](https://www.figma.com/file/JzKjcQ4Ptft5rhjc73NTKpdu/CoDaVi-Design-System?node-id=0%3A1) and [About](https://www.figma.com/file/xmsvph7F5fMJtx6CxgsT1f/About-Design?node-id=0%3A1) figma layouts. 
Keep an eye out for the "box module" paragraph style - the idea is to make a very versatile paragraph style that can be implemented differently to give different results. You can find it used for...

- [About](https://www.figma.com/file/xmsvph7F5fMJtx6CxgsT1f/About-Design?node-id=73%3A9): Stimmen, noch fragen
- [Event modules](https://www.figma.com/file/W0R4yR7orXG7JhEXlw3Mv6/EventPage-Modules?node-id=0%3A1): boxes, contact box, prizes
- [Landing page](https://www.figma.com/file/92ojS2H8Zjh7zoNY6BeyO1/LandingPage-Final?node-id=246%3A10): Jetzt anmelden

hope it can work out that way...

**Comment by Snater** [comment]
OK, thanks for the hint. I think we can have some general implementation for the boxes. There would be an optional header image and there needs to be a field to specify the background colour. The body will probably just be a rich text field. And then there seems to be an optional footer as well.

I am picking up the award winners first, so I could close the project related issues on that.

**Comment by Snater** [comment]
That box group seems to work very well, except in Internet Explorer. I will have to do a IE roundup anyhow.  Will get dirty.

**Comment by Snater** [comment]
This is about to be done. Todos left:
- Timeline module
- Header

**Comment by Snater** [comment]
Timeline module is done. Only header left on this ticket.

**Comment by lohengruen** [comment]
Here are the tiles for the header animation:
https://www.dropbox.com/s/v3khfk8foz5ukcw/Tiles_Event_small.jpg?dl=0

In contrast to the landing page header, there are fewer but bigger tiles for the event header. I've used a 400px size for each square and removed the white space between them to keep file size low.

The idea behind the event header is that users can easily create their own versions. I've included a small tutorial on how to replace images directly in the [Figma file](https://www.figma.com/file/GpZokmNZCxSUrcPoyzb3zOEe/Header-Images?node-id=102%3A0). There, users can export a new Tiles.jpg file, which they can then upload to the event page. If possible, this should be done by a simple "Replace background image" button in the backend.

**Comment by lohengruen** [comment]
In the backend, there should also be an option to customise the color overlay for the header animation. This is a full size gradient, that runs from top to bottom of the header. The bottom color is always "#F1ECE8" and the top color can be selected from the individual colour scheme. 
`background: linear-gradient(180deg, #F1ECE8 0%, #5DC4B8 100%);
mix-blend-mode: multiply;
opacity: 0.75;`

See the [Figma file](https://www.figma.com/file/W0R4yR7orXG7JhEXlw3Mv6/EventPage-Modules?node-id=1%3A2) for reference (Header > Gradient)

**Comment by Snater** [comment]
Default header is implemented. Just need a field here for uploading an individual header file. I edited the static header files so they behave like a pattern without seams on the edges. The current page does not have it like that, but I think its nicer. I think it's sufficient for event organizers to just upload that compiled front tiles image and leave that static background the same on every event page. I will implement it like that.

**Comment by lohengruen** [comment]
Good idea with the continuous tiling! And I agree, there is probably no need to customise the static background.

**Comment by Snater** [comment]
Option to customize header is implemented--seems like this ticket is about to be done as well for now. Just missing regional identity implementation here.

**Comment by Snater** [comment]
Implemented additional fields on the event content type to capture regional identity. Currently, the two colours are applied to the header and to the winners list. Applying color to addition fields would not be a big effort.
