### ISSUE TITLE
Always use select box on license fields

### ISSUE THREAD

**Issue by Snater** [codingdavinci/relaunch2018#58]
Replace license name auto-completion with select box.

**Comment by lucyWMDE** [comment]
Namensnennung field only shows only when CC-BY

**Comment by lucyWMDE** [comment]
Reopening... see my comment above.

**Comment by Snater** [comment]
OK, but that's implemented. It's already on staging and works for me. The "Namensnennung" field gets hidden when "gemeinfrei" is selected as license. Or was that about something else?

**Comment by lucyWMDE** [comment]
I was testing with CC0... if you can set it for that as well then we're good :) 
btw I liked the 1-line layout you use for Lizenz der Mediendateien, dataset submission. Would be happy if we used that everywhere...

**Comment by Snater** [comment]
Ah! OK, I can to that for CC0 as well, no problem. I just had read on CC0 at some point that an attribution may be supplied, but is optional for the user to name.
I will apply the attribution one-line layout to the "attributed image" as well. That should be the only other field type with attribution.

**Comment by lucyWMDE** [comment]
Yes... we've just been talking about it... the example of unsplash came up - there if you go to download a CC0 image it gives you a little popup with the advice, "Crediting isn’t required, but is appreciated and allows photographers to gain exposure. Copy the text below or embed a credit badge." 
Proposing optional crediting for CC0 licensed datasets would also be cool for us (more encouraging for the institutions)... That would mean adjusting the presentation for CC0 licensed datasets only so that an extra sentence appears near the Namensnennung field... would that be possible? If it's a bunch of extra work then it's probably not worth it however...

**Comment by Snater** [comment]
No problemo. I will add additional markup to the output and the sentence will also be marked for translation.

**Comment by Snater** [comment]
I have moved the attribution on images into the line of the license select box,
