### ISSUE TITLE
Event page header: centre the banner

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#88]
We also talked about this at an earlier stage. We agreed to try and center the banner in the middle of the screen. At the moment the banner is too high in page on big screens. 
![image](https://user-images.githubusercontent.com/42772674/59778861-8cc67e80-92b7-11e9-9572-9a09f68f05e9.png)

**Comment by Snater** [comment]
I've just increased the top padding. The overall layout concept is quite complex. It would be possible to use JavaScript to center the box between the bottom edge of the menu bar and the top edge of the content, but that's also not what is supposed to happen, because on certain viewport sizes the top edge of the content is not even visible. Positioning the header box is kind of finding a compromise in respect to viewport sizes/breakpoints. A lot of time could be spent on this while still not getting it perfect. I'd stick with finding a proper top padding—just check if it would be OK as it is now on staging. We could of course increase the top padding still a bit more on large screens.

**Comment by Snater** [comment]
Closing for now, just reopen if it should be different or if it does not fit yet.
